name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  gofmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Run gofmt
        run: |
          find . -name '*.go' -exec gofmt -s -w {} +
      - name: Commit formatted code
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "format code automatically" || echo "No changes to commit"
          git push
